name: Internal Issue Management

on:
  issues:
    types: 
      - labeled

jobs:
  internal:
    if: github.event.label.name == 'v2.0_first_inner_test'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Auto-assign Issue
        uses: pozil/auto-assign-issue@v2.2.0
        with:
          assignees: shiftonetothree,kang0x0,lok-ziming,Jzw-2001
          allowSelfAssign: true

      - name: Add issue to Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/ai-learning-assistant-dev/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
