name: Internal Issue Management

on:
  issues:
    types: 
      - labeled
      - opened
      - reopened

jobs:
  internal:
    if: github.event.label.name == 'v2.0_first_inner_test'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Assign internal owner
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.ADD_LABEL_TOKEN }}
          assignees: |
            shiftonetothree 
            kang0x0 
            lok-ziming
            Jzw-2001

      - name: Add issue to Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/ai-learning-assistant-dev/projects/5
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
