name: Apply label from issue form

on:
  issues:
    types: 
      - opened
      - reopened

jobs:
  extract:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Extract version field
        uses: actions-ecosystem/action-regex-match@v2
        id: match
        with:
          text: "${{ github.event.issue.body }}"
          regex: "### AI学习助手版本\\s*(.*)"

      - name: Add label based on version
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        if: steps.match.outputs.match != ''
        env:
          GH_TOKEN: ${{ secrets.ADD_LABEL_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ${{ steps.match.outputs.group1 }}
 
